image:
  formats: ["original", "webp"]
  loading: lazy
  layout: responsive
  objectFit: cover
  minWidth: 500
  maxWidth: 4000
  deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840]
  imageSizes: [16, 32, 48, 64, 96, 128, 256, 384]
  css: #css properties for the images
  placeholder:
    style: blur # empty | color | blur | solid (blur/solid js or inline type only)
    type: js  # css | js | inline
    blur:
      amount: 3
      size: 50
    # nativePlaceholder: none or colour value
    # libraryPlaceholder: blur, none, colour
  link:
    class:
    rel: 
    target: 
    css:
  figure:
    class: figure # .figureCSS to target figures
    titleClass: h4
    imageClass: figure-img
    figcaptionClass: figure-caption
    attrLinkClass:
    css:
  lazyLibrary:
    enable: true
    dataSrcset: true
    dataSrc: true
    dataSizes: true
    class: lazyload # can be array/slice
    loadingClass: lazyloading
    loadedClass: lazyloaded # used for blur-up
    blurUp: true
    imageCSS:
    figureCSS: "display:block!important;"
    noscript: true