
image:
  formats: ["original", "webp"]
  placeholder:
    style: blur # empty | color | blur | solid (blur/solid js or inline type only)
    type: inline  # css | js | inline
    blur:
      amount: 6 
      size: 50

    # nativePlaceholder: none or colour value
    # libraryPlaceholder: blur, none, colour
  loading: lazy
  minWidth: 500
  maxWidth: 4000
  deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840]
  imageSizes: [16, 32, 48, 64, 96, 128, 256, 384]
  link:
    class:
    rel: 
    target:  
  figure:
    class: figure # .figureCSS to target figures
    titleClass: h4
    imageClass: figure-img
    figcaptionClass: figure-caption
    attrLinkClass: ""
  lazyLibrary:
    enable: true  
    dataSrcSet: true
    dataSrc: true
    dataSizes: true
    class: lazysizes # can be array/slice
    #  imageCSS: "display:block;width:100%;" # add to css, but configure here?
    #  figureCSS: "display:block!important;" # add to css, but configure here? img.image and figure.[figure.class] (takes )
    # add to css 
    # $lazyLibraryFigureStyle := site.Params.image.lazyLibrary.figureStyle
    noscript: false