image:
  widths: [600, 900, 1300]
  # shortcodeWidths: [600, 900, 1300] # custom widths for shortcode use in markdown files
  # renderHookWidths: [600, 900, 1300] # custom widths for render hook use in markdown files
  densities: [1,2] # densities which are output when an image width is specified
  # outputFormats: [original, webp] # feature to be added
  class: img-fluid # default image class if no class is specified
  figureClass: figure # default figure class
  figcaptionClass: figure-caption # default figcaption class
  figureImageClass: figure-img # default figure image class (appended to image class)
  lazysizes: true # enable integration of the lazysizes js library
  renderHook: false # set to false to disable included markdown image render hook
